### ISSUE TITLE
GET QUOTE for HIRE 120 ton Hydraulic Truck Crane - 12-10-2017

### ISSUE THREAD

**Issue by ceobei** [beiquotes/BeiQuotes#11]
Purpose of Quote: hire
Category: Cranes
Sub category: Hydraulic Truck Crane
Location: Jalgaon, Maharashtra, India
What Best Describes Your Job? : ready to use
Start Date : 2017-10-12
Duration : 1 day
Comments : Bridge Erection at Jalgaon. Need Urgently
Which Best Describes Your Job? : commercial
Name : S.K. Pathak
Email : skpathak5@yahoo.in
Phone : 9860163414

**Comment by ceobei** [comment]
PRASANT this ticket is assigned to you close it by today

**Comment by beiquotes** [comment]
Ok sir

**Comment by beiquotes** [comment]
Just had word with Mr. Pathak on Phone as per him he posted the enquiry
yesterday and his work is done.

**Comment by beiquotes** [comment]
Mr. S.K. Pathak had closed deal with one of the local vendor for 120 ton hydraulic truck crane.

Re
