### ISSUE TITLE
CHECK AVAILABILITY request for Dumpers - HIRE on 29-11-2017 - 18:46PM

### ISSUE THREAD

**Issue by degeqp** [beiquotes/BeiQuotes#112]
ORDER DETAILS :
Order ID: DRC0025X000C5
Order Type: Hire
From: 12-01-2017
To: 03-01-2018
Created on: 11-29-2017
Comments: required for sand

PRODUCT DETAILS : 
Product ID: DRC0025H00218
Hire Price: PRICE ON REQUEST/Monthly
Capacity: 25 Tons
Category: Dumpers
Sub category: Road Construction
Model: Tata
Location: Maharashtra, India
Registered Number: Not Available
Life Tax Details: Not Available
Manufacture year: Not Available
Number of axles: Not Available
Dimensions: 0x0x0

ORDER OWNER DETAILS : 
Name: Udbhav
Email: udbhav.uniworks@gmail.com
Phone: 9560188567
Company Name: Uniworks
Company Address: Balewadi, Pune, Maharashtra
Designation: Partner
Company Email: udbhav.uniworks@gmail.com

PRODUCT OWNER DETAILS : 
Name: Vishwas
Email: sukhkarta3258@gmail.com
Phone: 9823298419
Company Name: Sukh Karta Construction
Company Address: Maharastra
Designation: NA
Company Email: NA

**Comment by beiquotes** [comment]
Duplicate Issue- #111

**Comment by degeqp** [comment]
Closing this check availability request since its said to be Duplicate issue by Sales Team.
