### ISSUE TITLE
New CONTACT INFO on 03-12-2017 - 9:19 a.m

### ISSUE THREAD

**Issue by degeqp** [beiquotes/BeiQuotes#123]
Kindly Follow-Up

Contacted By :- Subhasis jena 
Mobile No :- 9777745747 
Email Id :- shreeagencies.subhasis@gmail.com
Message :- 
I give rent basics my case 770dx soil compator roller odisha

**Comment by beiquotes** [comment]
company Name - shree Agency

He Needs Grader for 6 months at Orissa. This equipments is not available with us.

Work Description - Road Construction Leveling.

Prashant.
