### ISSUE TITLE
GET QUOTE for BUY - Excavator

### ISSUE THREAD

**Issue by degeqp** [beiquotes/BeiQuotes#62]
Purpose of Quote : buy
Category : Excavators
Sub category : Crawlers&Compact
Location : Aurangabad, Maharashtra, India
What Best Describes Your Job? : planning for budgeting
Start Date : 2017-12-01
Comments : Roadworks 
Which Best Describes Your Job? : doit yourself
Name : Sachin
Email : sachin_pc@me.com
Phone : 8600860011

**Comment by beiquotes** [comment]
Duplicate Enquiry

ISSUE NO - 61

Prashant
